{
//=========Macro generated from canvas: cTotErrorRMSbarlow/cTotErrorRMSbarlow
//=========  (Sat Jan 14 15:17:36 2017) by ROOT version5.34/30
   TCanvas *cTotErrorRMSbarlow = new TCanvas("cTotErrorRMSbarlow", "cTotErrorRMSbarlow",184,105,800,500);
   cTotErrorRMSbarlow->Range(-0.2964286,-0.0625,7.810714,0.5625);
   cTotErrorRMSbarlow->SetFillColor(0);
   cTotErrorRMSbarlow->SetBorderMode(0);
   cTotErrorRMSbarlow->SetBorderSize(2);
   cTotErrorRMSbarlow->SetFrameBorderMode(0);
   cTotErrorRMSbarlow->SetFrameBorderMode(0);
   Double_t xAxis1[8] = {1.2, 2, 2.5, 3, 3.5, 4, 5, 6}; 
   
   TH1D *SysErrorCutPercentileRMS1__1 = new TH1D("SysErrorCutPercentileRMS1__1","",7, xAxis1);
   SysErrorCutPercentileRMS1__1->SetBinContent(1,0.01572563);
   SysErrorCutPercentileRMS1__1->SetBinContent(2,0.06797399);
   SysErrorCutPercentileRMS1__1->SetBinContent(3,2.25449e-05);
   SysErrorCutPercentileRMS1__1->SetBinContent(4,0.02677534);
   SysErrorCutPercentileRMS1__1->SetBinContent(5,0.02745762);
   SysErrorCutPercentileRMS1__1->SetBinContent(6,0.06867878);
   SysErrorCutPercentileRMS1__1->SetBinContent(7,0.048633);
   SysErrorCutPercentileRMS1__1->SetMaximum(0.5);
   SysErrorCutPercentileRMS1__1->SetEntries(7);
   SysErrorCutPercentileRMS1__1->SetDirectory(0);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("SysErrorCutPercentileRMS1");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 7      ");
   text = ptstats->AddText("Mean  =  3.701");
   text = ptstats->AddText("RMS   =  1.282");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   SysErrorCutPercentileRMS1__1->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(SysErrorCutPercentileRMS1__1);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ff0000");
   SysErrorCutPercentileRMS1__1->SetLineColor(ci);
   SysErrorCutPercentileRMS1__1->SetLineWidth(2);

   ci = TColor::GetColor("#ff0000");
   SysErrorCutPercentileRMS1__1->SetMarkerColor(ci);
   SysErrorCutPercentileRMS1__1->SetMarkerStyle(22);
   SysErrorCutPercentileRMS1__1->GetXaxis()->SetTitle("p_{T} (GeV/c)");
   SysErrorCutPercentileRMS1__1->GetXaxis()->SetRange(0,8);
   SysErrorCutPercentileRMS1__1->GetXaxis()->SetLabelFont(42);
   SysErrorCutPercentileRMS1__1->GetXaxis()->SetLabelSize(0.035);
   SysErrorCutPercentileRMS1__1->GetXaxis()->SetTitleSize(0.035);
   SysErrorCutPercentileRMS1__1->GetXaxis()->SetTitleFont(42);
   SysErrorCutPercentileRMS1__1->GetYaxis()->SetTitle("Uncertainty(fraction)");
   SysErrorCutPercentileRMS1__1->GetYaxis()->SetLabelFont(42);
   SysErrorCutPercentileRMS1__1->GetYaxis()->SetLabelSize(0.035);
   SysErrorCutPercentileRMS1__1->GetYaxis()->SetTitleSize(0.035);
   SysErrorCutPercentileRMS1__1->GetYaxis()->SetTitleFont(42);
   SysErrorCutPercentileRMS1__1->GetZaxis()->SetLabelFont(42);
   SysErrorCutPercentileRMS1__1->GetZaxis()->SetLabelSize(0.035);
   SysErrorCutPercentileRMS1__1->GetZaxis()->SetTitleSize(0.035);
   SysErrorCutPercentileRMS1__1->GetZaxis()->SetTitleFont(42);
   SysErrorCutPercentileRMS1__1->Draw("");
   Double_t xAxis2[8] = {1.2, 2, 2.5, 3, 3.5, 4, 5, 6}; 
   
   TH1D *SumSystematicErrorFitVariationRMSbarlow__2 = new TH1D("SumSystematicErrorFitVariationRMSbarlow__2","SumSystematicErrorFitVariationRMSbarlow",7, xAxis2);
   SumSystematicErrorFitVariationRMSbarlow__2->SetBinContent(1,0.07290265);
   SumSystematicErrorFitVariationRMSbarlow__2->SetBinContent(2,0.03297589);
   SumSystematicErrorFitVariationRMSbarlow__2->SetBinContent(3,0.1680354);
   SumSystematicErrorFitVariationRMSbarlow__2->SetBinContent(4,0.1389751);
   SumSystematicErrorFitVariationRMSbarlow__2->SetBinContent(5,0.09201294);
   SumSystematicErrorFitVariationRMSbarlow__2->SetBinContent(6,0.1153965);
   SumSystematicErrorFitVariationRMSbarlow__2->SetBinContent(7,0.1540711);
   SumSystematicErrorFitVariationRMSbarlow__2->SetEntries(7);
   SumSystematicErrorFitVariationRMSbarlow__2->SetDirectory(0);

   ci = TColor::GetColor("#ff9900");
   SumSystematicErrorFitVariationRMSbarlow__2->SetLineColor(ci);
   SumSystematicErrorFitVariationRMSbarlow__2->SetLineWidth(2);
   SumSystematicErrorFitVariationRMSbarlow__2->GetXaxis()->SetTitle("p_{T} (GeV/c)");
   SumSystematicErrorFitVariationRMSbarlow__2->GetXaxis()->SetLabelFont(42);
   SumSystematicErrorFitVariationRMSbarlow__2->GetXaxis()->SetLabelSize(0.035);
   SumSystematicErrorFitVariationRMSbarlow__2->GetXaxis()->SetTitleSize(0.035);
   SumSystematicErrorFitVariationRMSbarlow__2->GetXaxis()->SetTitleFont(42);
   SumSystematicErrorFitVariationRMSbarlow__2->GetYaxis()->SetTitle("Uncertainty (fraction)");
   SumSystematicErrorFitVariationRMSbarlow__2->GetYaxis()->SetLabelFont(42);
   SumSystematicErrorFitVariationRMSbarlow__2->GetYaxis()->SetLabelSize(0.035);
   SumSystematicErrorFitVariationRMSbarlow__2->GetYaxis()->SetTitleSize(0.035);
   SumSystematicErrorFitVariationRMSbarlow__2->GetYaxis()->SetTitleFont(42);
   SumSystematicErrorFitVariationRMSbarlow__2->GetZaxis()->SetLabelFont(42);
   SumSystematicErrorFitVariationRMSbarlow__2->GetZaxis()->SetLabelSize(0.035);
   SumSystematicErrorFitVariationRMSbarlow__2->GetZaxis()->SetTitleSize(0.035);
   SumSystematicErrorFitVariationRMSbarlow__2->GetZaxis()->SetTitleFont(42);
   SumSystematicErrorFitVariationRMSbarlow__2->Draw("same");
   Double_t xAxis3[8] = {1.2, 2, 2.5, 3, 3.5, 4, 5, 6}; 
   
   TH1D *SumSystematicErrorTopologyRMSbarlow__3 = new TH1D("SumSystematicErrorTopologyRMSbarlow__3","SumSystematicErrorTopologyRMSbarlow",7, xAxis3);
   SumSystematicErrorTopologyRMSbarlow__3->SetBinContent(1,0.08547645);
   SumSystematicErrorTopologyRMSbarlow__3->SetBinContent(2,0.09092208);
   SumSystematicErrorTopologyRMSbarlow__3->SetBinContent(3,3.517227e-05);
   SumSystematicErrorTopologyRMSbarlow__3->SetBinContent(4,0.07821764);
   SumSystematicErrorTopologyRMSbarlow__3->SetBinContent(5,0.09588305);
   SumSystematicErrorTopologyRMSbarlow__3->SetBinContent(6,0.0607662);
   SumSystematicErrorTopologyRMSbarlow__3->SetBinContent(7,0.1118378);
   SumSystematicErrorTopologyRMSbarlow__3->SetEntries(7);
   SumSystematicErrorTopologyRMSbarlow__3->SetDirectory(0);

   ci = TColor::GetColor("#009900");
   SumSystematicErrorTopologyRMSbarlow__3->SetLineColor(ci);
   SumSystematicErrorTopologyRMSbarlow__3->SetLineWidth(2);
   SumSystematicErrorTopologyRMSbarlow__3->GetXaxis()->SetTitle("p_{T} (GeV/c)");
   SumSystematicErrorTopologyRMSbarlow__3->GetXaxis()->SetLabelFont(42);
   SumSystematicErrorTopologyRMSbarlow__3->GetXaxis()->SetLabelSize(0.035);
   SumSystematicErrorTopologyRMSbarlow__3->GetXaxis()->SetTitleSize(0.035);
   SumSystematicErrorTopologyRMSbarlow__3->GetXaxis()->SetTitleFont(42);
   SumSystematicErrorTopologyRMSbarlow__3->GetYaxis()->SetTitle("Uncertainty (fraction)");
   SumSystematicErrorTopologyRMSbarlow__3->GetYaxis()->SetLabelFont(42);
   SumSystematicErrorTopologyRMSbarlow__3->GetYaxis()->SetLabelSize(0.035);
   SumSystematicErrorTopologyRMSbarlow__3->GetYaxis()->SetTitleSize(0.035);
   SumSystematicErrorTopologyRMSbarlow__3->GetYaxis()->SetTitleFont(42);
   SumSystematicErrorTopologyRMSbarlow__3->GetZaxis()->SetLabelFont(42);
   SumSystematicErrorTopologyRMSbarlow__3->GetZaxis()->SetLabelSize(0.035);
   SumSystematicErrorTopologyRMSbarlow__3->GetZaxis()->SetTitleSize(0.035);
   SumSystematicErrorTopologyRMSbarlow__3->GetZaxis()->SetTitleFont(42);
   SumSystematicErrorTopologyRMSbarlow__3->Draw("same");
   Double_t xAxis4[8] = {1.2, 2, 2.5, 3, 3.5, 4, 5, 6}; 
   
   TH1D *SysErrorPIDPercentileRMS__4 = new TH1D("SysErrorPIDPercentileRMS__4","SysErrorPIDPercentileRMS",7, xAxis4);
   SysErrorPIDPercentileRMS__4->SetBinContent(1,0.1083589);
   SysErrorPIDPercentileRMS__4->SetBinContent(2,0.04236394);
   SysErrorPIDPercentileRMS__4->SetBinContent(3,0.01351125);
   SysErrorPIDPercentileRMS__4->SetBinContent(4,0.149124);
   SysErrorPIDPercentileRMS__4->SetBinContent(5,0.1741377);
   SysErrorPIDPercentileRMS__4->SetBinContent(6,0.1231307);
   SysErrorPIDPercentileRMS__4->SetBinContent(7,0.04295167);
   SysErrorPIDPercentileRMS__4->SetMaximum(0.2);
   SysErrorPIDPercentileRMS__4->SetEntries(7);
   SysErrorPIDPercentileRMS__4->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   SysErrorPIDPercentileRMS__4->SetLineColor(ci);
   SysErrorPIDPercentileRMS__4->SetLineWidth(2);
   SysErrorPIDPercentileRMS__4->GetXaxis()->SetTitle("p_{T} (GeV/c)");
   SysErrorPIDPercentileRMS__4->GetXaxis()->SetRange(0,8);
   SysErrorPIDPercentileRMS__4->GetXaxis()->SetLabelFont(42);
   SysErrorPIDPercentileRMS__4->GetXaxis()->SetLabelSize(0.035);
   SysErrorPIDPercentileRMS__4->GetXaxis()->SetTitleSize(0.035);
   SysErrorPIDPercentileRMS__4->GetXaxis()->SetTitleFont(42);
   SysErrorPIDPercentileRMS__4->GetYaxis()->SetLabelFont(42);
   SysErrorPIDPercentileRMS__4->GetYaxis()->SetLabelSize(0.035);
   SysErrorPIDPercentileRMS__4->GetYaxis()->SetTitleSize(0.035);
   SysErrorPIDPercentileRMS__4->GetYaxis()->SetTitleFont(42);
   SysErrorPIDPercentileRMS__4->GetZaxis()->SetLabelFont(42);
   SysErrorPIDPercentileRMS__4->GetZaxis()->SetLabelSize(0.035);
   SysErrorPIDPercentileRMS__4->GetZaxis()->SetTitleSize(0.035);
   SysErrorPIDPercentileRMS__4->GetZaxis()->SetTitleFont(42);
   SysErrorPIDPercentileRMS__4->Draw("same");
   Double_t xAxis5[8] = {1.2, 2, 2.5, 3, 3.5, 4, 5, 6}; 
   
   TH1D *SysErrorReweighEffi__5 = new TH1D("SysErrorReweighEffi__5","SysErrorReweighEffi",7, xAxis5);
   SysErrorReweighEffi__5->SetBinContent(1,0.07099754);
   SysErrorReweighEffi__5->SetBinContent(2,0.00295185);
   SysErrorReweighEffi__5->SetBinContent(3,0.0009486955);
   SysErrorReweighEffi__5->SetBinContent(4,0.0005145047);
   SysErrorReweighEffi__5->SetBinContent(5,8.784149e-05);
   SysErrorReweighEffi__5->SetBinContent(6,0.001140837);
   SysErrorReweighEffi__5->SetBinContent(7,0.03867771);
   SysErrorReweighEffi__5->SetEntries(7);
   SysErrorReweighEffi__5->SetDirectory(0);

   ci = TColor::GetColor("#660099");
   SysErrorReweighEffi__5->SetLineColor(ci);
   SysErrorReweighEffi__5->SetLineWidth(2);
   SysErrorReweighEffi__5->GetXaxis()->SetLabelFont(42);
   SysErrorReweighEffi__5->GetXaxis()->SetLabelSize(0.035);
   SysErrorReweighEffi__5->GetXaxis()->SetTitleSize(0.035);
   SysErrorReweighEffi__5->GetXaxis()->SetTitleFont(42);
   SysErrorReweighEffi__5->GetYaxis()->SetLabelFont(42);
   SysErrorReweighEffi__5->GetYaxis()->SetLabelSize(0.035);
   SysErrorReweighEffi__5->GetYaxis()->SetTitleSize(0.035);
   SysErrorReweighEffi__5->GetYaxis()->SetTitleFont(42);
   SysErrorReweighEffi__5->GetZaxis()->SetLabelFont(42);
   SysErrorReweighEffi__5->GetZaxis()->SetLabelSize(0.035);
   SysErrorReweighEffi__5->GetZaxis()->SetTitleSize(0.035);
   SysErrorReweighEffi__5->GetZaxis()->SetTitleFont(42);
   SysErrorReweighEffi__5->Draw("same");
   Double_t xAxis6[8] = {1.2, 2, 2.5, 3, 3.5, 4, 5, 6}; 
   
   TH1D *SysErrorMBPercentileRMS__6 = new TH1D("SysErrorMBPercentileRMS__6","SysErrorMBPercentileRMS",7, xAxis6);
   SysErrorMBPercentileRMS__6->SetBinContent(1,0.04);
   SysErrorMBPercentileRMS__6->SetBinContent(2,0.04);
   SysErrorMBPercentileRMS__6->SetBinContent(3,0.04);
   SysErrorMBPercentileRMS__6->SetBinContent(4,0.04);
   SysErrorMBPercentileRMS__6->SetBinContent(5,0.04);
   SysErrorMBPercentileRMS__6->SetBinContent(6,0.04);
   SysErrorMBPercentileRMS__6->SetBinContent(7,0.04);
   SysErrorMBPercentileRMS__6->SetBinContent(8,0.04);
   SysErrorMBPercentileRMS__6->SetEntries(10);
   SysErrorMBPercentileRMS__6->SetDirectory(0);

   ci = TColor::GetColor("#999999");
   SysErrorMBPercentileRMS__6->SetLineColor(ci);
   SysErrorMBPercentileRMS__6->SetLineWidth(2);
   SysErrorMBPercentileRMS__6->GetXaxis()->SetLabelFont(42);
   SysErrorMBPercentileRMS__6->GetXaxis()->SetLabelSize(0.035);
   SysErrorMBPercentileRMS__6->GetXaxis()->SetTitleSize(0.035);
   SysErrorMBPercentileRMS__6->GetXaxis()->SetTitleFont(42);
   SysErrorMBPercentileRMS__6->GetYaxis()->SetLabelFont(42);
   SysErrorMBPercentileRMS__6->GetYaxis()->SetLabelSize(0.035);
   SysErrorMBPercentileRMS__6->GetYaxis()->SetTitleSize(0.035);
   SysErrorMBPercentileRMS__6->GetYaxis()->SetTitleFont(42);
   SysErrorMBPercentileRMS__6->GetZaxis()->SetLabelFont(42);
   SysErrorMBPercentileRMS__6->GetZaxis()->SetLabelSize(0.035);
   SysErrorMBPercentileRMS__6->GetZaxis()->SetTitleSize(0.035);
   SysErrorMBPercentileRMS__6->GetZaxis()->SetTitleFont(42);
   SysErrorMBPercentileRMS__6->Draw("same");
   Double_t xAxis7[8] = {1.2, 2, 2.5, 3, 3.5, 4, 5, 6}; 
   
   TH1D *SysErrorTrackingEffPercentileRMS__7 = new TH1D("SysErrorTrackingEffPercentileRMS__7","SysErrorTrackingEffPercentileRMS",7, xAxis7);
   SysErrorTrackingEffPercentileRMS__7->SetBinContent(1,0.04);
   SysErrorTrackingEffPercentileRMS__7->SetBinContent(2,0.04);
   SysErrorTrackingEffPercentileRMS__7->SetBinContent(3,0.04);
   SysErrorTrackingEffPercentileRMS__7->SetBinContent(4,0.04);
   SysErrorTrackingEffPercentileRMS__7->SetBinContent(5,0.04);
   SysErrorTrackingEffPercentileRMS__7->SetBinContent(6,0.04);
   SysErrorTrackingEffPercentileRMS__7->SetBinContent(7,0.04);
   SysErrorTrackingEffPercentileRMS__7->SetBinContent(8,0.04);
   SysErrorTrackingEffPercentileRMS__7->SetEntries(10);
   SysErrorTrackingEffPercentileRMS__7->SetDirectory(0);

   ci = TColor::GetColor("#ff66ff");
   SysErrorTrackingEffPercentileRMS__7->SetLineColor(ci);
   SysErrorTrackingEffPercentileRMS__7->SetLineWidth(2);
   SysErrorTrackingEffPercentileRMS__7->GetXaxis()->SetLabelFont(42);
   SysErrorTrackingEffPercentileRMS__7->GetXaxis()->SetLabelSize(0.035);
   SysErrorTrackingEffPercentileRMS__7->GetXaxis()->SetTitleSize(0.035);
   SysErrorTrackingEffPercentileRMS__7->GetXaxis()->SetTitleFont(42);
   SysErrorTrackingEffPercentileRMS__7->GetYaxis()->SetLabelFont(42);
   SysErrorTrackingEffPercentileRMS__7->GetYaxis()->SetLabelSize(0.035);
   SysErrorTrackingEffPercentileRMS__7->GetYaxis()->SetTitleSize(0.035);
   SysErrorTrackingEffPercentileRMS__7->GetYaxis()->SetTitleFont(42);
   SysErrorTrackingEffPercentileRMS__7->GetZaxis()->SetLabelFont(42);
   SysErrorTrackingEffPercentileRMS__7->GetZaxis()->SetLabelSize(0.035);
   SysErrorTrackingEffPercentileRMS__7->GetZaxis()->SetTitleSize(0.035);
   SysErrorTrackingEffPercentileRMS__7->GetZaxis()->SetTitleFont(42);
   SysErrorTrackingEffPercentileRMS__7->Draw("same");
   Double_t xAxis8[8] = {1.2, 2, 2.5, 3, 3.5, 4, 5, 6}; 
   
   TH1D *SysErrorHadronicInteractionRMS__8 = new TH1D("SysErrorHadronicInteractionRMS__8","SysErrorHadronicInteractionRMS",7, xAxis8);
   SysErrorHadronicInteractionRMS__8->SetBinContent(1,0.01);
   SysErrorHadronicInteractionRMS__8->SetBinContent(2,0.01);
   SysErrorHadronicInteractionRMS__8->SetBinContent(3,0.01);
   SysErrorHadronicInteractionRMS__8->SetBinContent(4,0.01);
   SysErrorHadronicInteractionRMS__8->SetBinContent(5,0.01);
   SysErrorHadronicInteractionRMS__8->SetBinContent(6,0.01);
   SysErrorHadronicInteractionRMS__8->SetBinContent(7,0.01);
   SysErrorHadronicInteractionRMS__8->SetBinContent(8,0.01);
   SysErrorHadronicInteractionRMS__8->SetEntries(10);
   SysErrorHadronicInteractionRMS__8->SetDirectory(0);

   ci = TColor::GetColor("#000099");
   SysErrorHadronicInteractionRMS__8->SetLineColor(ci);
   SysErrorHadronicInteractionRMS__8->SetLineWidth(2);
   SysErrorHadronicInteractionRMS__8->GetXaxis()->SetLabelFont(42);
   SysErrorHadronicInteractionRMS__8->GetXaxis()->SetLabelSize(0.035);
   SysErrorHadronicInteractionRMS__8->GetXaxis()->SetTitleSize(0.035);
   SysErrorHadronicInteractionRMS__8->GetXaxis()->SetTitleFont(42);
   SysErrorHadronicInteractionRMS__8->GetYaxis()->SetLabelFont(42);
   SysErrorHadronicInteractionRMS__8->GetYaxis()->SetLabelSize(0.035);
   SysErrorHadronicInteractionRMS__8->GetYaxis()->SetTitleSize(0.035);
   SysErrorHadronicInteractionRMS__8->GetYaxis()->SetTitleFont(42);
   SysErrorHadronicInteractionRMS__8->GetZaxis()->SetLabelFont(42);
   SysErrorHadronicInteractionRMS__8->GetZaxis()->SetLabelSize(0.035);
   SysErrorHadronicInteractionRMS__8->GetZaxis()->SetTitleSize(0.035);
   SysErrorHadronicInteractionRMS__8->GetZaxis()->SetTitleFont(42);
   SysErrorHadronicInteractionRMS__8->Draw("same");
   Double_t xAxis9[8] = {1.2, 2, 2.5, 3, 3.5, 4, 5, 6}; 
   
   TH1D *fSumSystematicErrorRMSbarlow__9 = new TH1D("fSumSystematicErrorRMSbarlow__9","fSumSystematicErrorRMSbarlow",7, xAxis9);
   fSumSystematicErrorRMSbarlow__9->SetBinContent(1,0.181523);
   fSumSystematicErrorRMSbarlow__9->SetBinContent(2,0.1381235);
   fSumSystematicErrorRMSbarlow__9->SetBinContent(3,0.1780993);
   fSumSystematicErrorRMSbarlow__9->SetBinContent(4,0.2273483);
   fSumSystematicErrorRMSbarlow__9->SetBinContent(5,0.228118);
   fSumSystematicErrorRMSbarlow__9->SetBinContent(6,0.2004698);
   fSumSystematicErrorRMSbarlow__9->SetBinContent(7,0.2127242);
   fSumSystematicErrorRMSbarlow__9->SetEntries(8);
   fSumSystematicErrorRMSbarlow__9->SetDirectory(0);
   fSumSystematicErrorRMSbarlow__9->SetLineStyle(4);
   fSumSystematicErrorRMSbarlow__9->SetLineWidth(4);
    fSumSystematicErrorRMSbarlow__9->SetLineColor(1);
   fSumSystematicErrorRMSbarlow__9->GetXaxis()->SetTitle("p_{T} (GeV/c)");
   fSumSystematicErrorRMSbarlow__9->GetXaxis()->SetLabelFont(42);
   fSumSystematicErrorRMSbarlow__9->GetXaxis()->SetLabelSize(0.035);
   fSumSystematicErrorRMSbarlow__9->GetXaxis()->SetTitleSize(0.035);
   fSumSystematicErrorRMSbarlow__9->GetXaxis()->SetTitleFont(42);
   fSumSystematicErrorRMSbarlow__9->GetYaxis()->SetTitle("Uncertainty (fraction)");
   fSumSystematicErrorRMSbarlow__9->GetYaxis()->SetLabelFont(42);
   fSumSystematicErrorRMSbarlow__9->GetYaxis()->SetLabelSize(0.035);
   fSumSystematicErrorRMSbarlow__9->GetYaxis()->SetTitleSize(0.035);
   fSumSystematicErrorRMSbarlow__9->GetYaxis()->SetTitleFont(42);
   fSumSystematicErrorRMSbarlow__9->GetZaxis()->SetLabelFont(42);
   fSumSystematicErrorRMSbarlow__9->GetZaxis()->SetLabelSize(0.035);
   fSumSystematicErrorRMSbarlow__9->GetZaxis()->SetTitleSize(0.035);
   fSumSystematicErrorRMSbarlow__9->GetZaxis()->SetTitleFont(42);
   fSumSystematicErrorRMSbarlow__9->Draw("same");
   
   TLegend *leg = new TLegend(0.5,0.55,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("fSumSystematicErrorRMS","Total","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(4);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("SysErrorCutPercentileRMS1","Sys. Track selection","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("SumSystematicErrorFitVariationRMS","Sys. Signal extraction","l");

   ci = TColor::GetColor("#ff9900");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("SumSystematicErrorTopologyRMS","Sys. Tolological selection","l");

   ci = TColor::GetColor("#009900");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("SysErrorPIDPercentileRMS","Sys. PID","l");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("SysErrorReweighEffi","Sys. #it{p}_{T} shape correction","l");

   ci = TColor::GetColor("#660099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("SysErrorMBPercentileRMS","Sys. Material budget","l");

   ci = TColor::GetColor("#999999");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("SysErrorTrackingEffPercentileRMS","Sys. Tracking efficiency (ITS/TPC)","l");

   ci = TColor::GetColor("#ff66ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("SysErrorHadronicInteractionRMS","Sys. Hadronic interaction","l");

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
      tex = new TLatex(0.15,0.85,"ALICE, Pb-Pb, #sqrt{s_{NN}} = 2.76 TeV");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.15,0.8,"|y| < 0.5");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.15,0.75,"V0M Centrality class (0-10%)");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();

   cTotErrorRMSbarlow->Modified();
   cTotErrorRMSbarlow->cd();
   cTotErrorRMSbarlow->SetSelected(cTotErrorRMSbarlow);
}
